package:
  name: 'termcolor-yf'
  description: 'Terminal coloring + style for Y-flat'
  version: 0.1.0
  url: 'https://github.com/JakeRoggenbuck/termcolor-yf'

  authors:
    - 'Jake Roggenbuck'

  license: 'MIT'

depends:
